<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Inicio.aspx.cs" Inherits="Blog.Inicio" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <br />
     <asp:Label ID="Label1" runat="server" Text="LISTA DE TEMAS" BackColor="#99CCFF" Font-Bold="True" Width="100%"></asp:Label>
     <br />
     <asp:Panel ID="Panel1" runat="server">
         <asp:Label ID="Label2" runat="server" Text="Nuevo tema:"></asp:Label>
         &nbsp;<asp:Label ID="Label4" runat="server" Text="Id: "></asp:Label>
         <asp:TextBox ID="TextBox1" runat="server" Width="62px"></asp:TextBox>
         <asp:Label ID="Label5" runat="server" Text="Nombre: "></asp:Label>
         <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
         <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Agregar" />
         <asp:Label ID="Label3" runat="server"></asp:Label>
         <asp:Button ID="Button2" runat="server" OnClick="Button2_Click" Text="Guardar cambios" Visible="False" />
         &nbsp;<asp:Button ID="Button3" runat="server" OnClick="Button3_Click" Text="Cancelar" Visible="False" />
     </asp:Panel>
     <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" OnRowDeleting="Borrar_click" OnRowEditing="Editar_click" ForeColor="#333333" GridLines="None">
         <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
         <Columns>
             <asp:BoundField DataField="idtema" HeaderText="No" />
             <asp:BoundField DataField="nombre" HeaderText="Nombre del tema" />
         </Columns>
         <EditRowStyle BackColor="#999999" />
         <FooterStyle BackColor="#5D7B9D" ForeColor="White" Font-Bold="True" />
         <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
         <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
         <RowStyle ForeColor="#333333" BackColor="#F7F6F3" />
         <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
         <SortedAscendingCellStyle BackColor="#E9E7E2" />
         <SortedAscendingHeaderStyle BackColor="#506C8C" />
         <SortedDescendingCellStyle BackColor="#FFFDF8" />
         <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
     </asp:GridView>
</asp:Content>
